import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';

export const initialState: any = {
  // Employement Details
  employementDescription: null,
  jobLetter: null,
  uploadSlip: null,
  visitingCard: null,
  businessDocument: null,
  appointmentLetter: null,
  bankStatement: null,
  employerKey: null,
  employerDesc: null,
  otherEmployer: null,
  employeeId: null,
  employmentDesc: null,
  dateOfJoining: null,
  employementOccupation: null,
  employementSectorId: null,
  employementSector: null,
  employmentTypeKeyId: null,
  employementType: null,
  salaryFrequencyKey: null,
  salaryFrequency: null,
  incomeRangeKey: null,
  incomeRangeKeyDesc: null,
  salary: null,
  employementSourceFund: null,
  employementSourceFundOthers: null,
  employerAddress1: null,
  employerAddress2: null,
  employerCity: null,
  employerCountryDesc: null,
  employerCountry: null,
  employerZipCode: null,
  employerWorkPhoneIsd: null,
  employerWorkPhoneIsdDesc: null,
  employerWorkPhone: null,
  employerWorkEmail: null,
  purposeOfBusiness: null,
};

export const memberOnboardingSlice = createSlice({
  name: 'memberOnboarding',
  initialState,
  reducers: {
    setState: (state, action: PayloadAction<any>) => {
      return (state = { ...state, ...action.payload });
    },
    resetState: state => {
      return (state = initialState);
    },
    resetStateInCheckList: state => {
      return (state = {
        primaryDocumentResponse: {
          passportNo: '',
          permitNumber: '',
          placeOfBirth: '',
          address: '',
          nationality: '',
          authority: '',
          surname: '',
          fullName: '',
          sex: '',
          dateOfBirth: '',
          dateOfIssue: '',
          dateOfExpiry: '',
          dateOfPayment: '',
          class: '',
          tr: '',
          age: '',
          remainderTerm: '',
          idType: '',
          country: '',
          countryCode: '',
          firstName: '',
          lastName: '',
          middleName: '',
          signaturebase64: '',
          proPicBese64: '',
        },
        secondaryDocumentResponse: {
          passportNo: '',
          permitNumber: '',
          placeOfBirth: '',
          address: '',
          nationality: '',
          authority: '',
          surname: '',
          fullName: '',
          sex: '',
          dateOfBirth: '',
          dateOfIssue: '',
          dateOfExpiry: '',
          dateOfPayment: '',
          class: '',
          tr: '',
          age: '',
          remainderTerm: '',
          idType: '',
          country: '',
          countryCode: '',
          firstName: '',
          lastName: '',
          middleName: '',
          signaturebase64: '',
          proPicBese64: '',
        },
        addressDocumentResponse: {},
        birthDocumentResponse: {},
        employementDescription: null,
        jobLetter: null,
        uploadSlip: null,
        visitingCard: null,
        businessDocument: null,
        appointmentLetter: null,
        bankStatement: null,
        employerKey: null,
        employerDesc: null,
        employeeId: null,
        employmentDesc: null,
        dateOfJoining: null,
        employementOccupation: null,
        employementSectorId: null,
        employementSector: null,
        employmentTypeKeyId: null,
        employementType: null,
        employementSourceFund: null,
        employementSourceFundOthers: null,
        employerAddress1: null,
        employerAddress2: null,
        employerCity: null,
        employerCountryDesc: null,
        employerCountry: null,
        employerZipCode: null,
        employerWorkPhoneIsd: null,
        employerWorkPhoneIsdDesc: null,
        employerWorkPhone: null,
        employerEmail: null,
        purposeOfBusiness: null,
        nationality1: '',
        primaryNationalityKeyId: '',
        nationality2: '',
        secondaryNationalityKeyId: '',
        countryOfBirth: '',
        countryOfBirthKeyId: '',
        placeOfBirth: '',
        placeOfBirthKeyId: '',
        education: '',
        highestEducationKeyId: '',
        spouseMemberID: '',
        spouseDOB: '',
        spouseFullName: '',
        spouseFirstName: '',
        spouseLastName: '',
        spousePhoneNumber: '',
        spousePhoneNumberIsd: '',
        spousePhoneNumberIsdDesc: '',

        // Joint Partner Details
        jointPartnerMemberId: '',
        jointPartnerDateOfBirth: '',
        jointPartnerFirstName: '',
        jointPartnerLastName: '',
        jointPartnerEmailId: '',
        jointPartnerMobileNo: '',
        jointPartnerMobileNoIsdKey: '',
        jointPartnerMobileNoIsd: '',
        relationWithJointPartner: '',
        relationWithJointPartnerID: '',
        isGreenCardHolder: true,
        isGranteePOA: false,
        isStandingInstructIncome: false,
        isDisclosureTaxResidency: false,
        fatcaCountry: '',
        fatcaCountryKeyId: '',
        ssnNo: '',
        beneficiaryMemberId: '',
        beneficiaryDateOfBirth: '',
        beneficiaryFullName: '',
        beneficiaryPhoneNumberIsd: '',
        beneficiaryPhoneNumber: '',
        relationWithBeneficiary: '',
        relationWithBeneficiaryID: '',
      });
    },
  },
});

export const { setState, resetState } = memberOnboardingSlice.actions;

export default memberOnboardingSlice.reducer;
