import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const styles = StyleSheet.create({
  HeaderContainer: {
    backgroundColor: "#fff",
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    borderBottomLeftRadius: wp(5),
    borderBottomRightRadius: wp(5),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  profileContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileImage: {
    height: hp(5.5),
    width: hp(5.5),
    borderRadius: hp(50),
    resizeMode: "contain",
  },
  welcomeBackText: {
    fontWeight: "bold",
    color: "black",
    fontSize: hp(1.8),
  },
  profileNameText: {
    color: "#7E4310",
    fontSize: hp(2.2),
    fontWeight: "600",
  },
  bellNotification: {
    height: hp(3.5),
    width: hp(3.5),
    resizeMode: "contain",
  },
  notificationBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    height: 10,
    width: 10,
    borderRadius: 5,
    backgroundColor: "red",
  },
  scrollViewContent: {
    paddingBottom: hp(2),
    paddingTop: hp(1),
  },
  taskOverviewSection: {
    paddingHorizontal: wp(4),
    marginTop: hp(2),
    backgroundColor: "white",
    borderRadius: hp(1),
    marginLeft: wp(3),
    marginRight: wp(3),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  taskOverviewHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp(0.5),
    marginTop: hp(1),
  },
  taskOverviewTitle: {
    fontWeight: "bold",
    fontSize: hp(2),
    color: "black",
    flex: 1,
  },
  taskOverviewDropdownWrapper: {
    alignItems: "flex-end",
    justifyContent: "center",
  },
  taskOverviewSubTitle: {
    fontSize: hp(1.5),
  },
  taskOverviewDropdown: {
    width: wp(25),
    backgroundColor: "#fff",
    borderRadius: hp(0.5),
    borderWidth: 0.5,
    borderColor: "#BFBFBF",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  taskOverviewProgressBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: hp(2),
  },
  taskOverviewProgressBar: {
    flex: 1,
    height: hp(1.2),
    borderRadius: hp(0.6),
    marginRight: wp(3),
  },
  taskOverviewProgressTextWrapper: {
    flexDirection: "column",
    alignItems: "flex-end",
  },
  taskOverviewProgressText: {
    fontWeight: "bold",
    color: "black",
    fontSize: hp(1.8),
  },
  taskOverviewCompletedLabel: {
    fontSize: hp(1.5),
    color: "#616264",
  },
  performanceOverView: {
    marginTop: hp(1),
    borderRadius: hp(1),
    marginLeft: wp(3),
    marginRight: wp(3),
    paddingVertical: hp(2),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    backgroundColor: "white",
    elevation: 3,
  },
  performanceOverviewSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: wp(4),
    marginTop: hp(1),
  },
  circularProgressWrapper: {
    height: hp(24),
    width: wp(26),
    alignItems: "flex-start",
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(2),
    backgroundColor: "#333333",
    borderRadius: wp(3),
  },
  circularProgressTitle: {
    color: "white",
    fontSize: wp(2.3),
    fontWeight: "bold",
    lineHeight: wp(3.2),
    marginBottom: hp(1.5),
  },
  circularProgressContainer: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    alignSelf: "center",
    marginBottom: hp(1),
  },
  circularProgressTextWrapper: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  circularProgressMainValue: {
    fontSize: wp(4),
    fontWeight: "bold",
    color: "white",
  },
  circularProgressTotalValue: {
    fontSize: wp(2.5),
    fontWeight: "500",
    color: "#BDC3C7",
    marginTop: wp(1),
  },
  circularProgressLabel: {
    fontSize: wp(2),
    color: "white",
    fontWeight: "600",
    marginBottom: hp(0.3),
    alignSelf: "center",
  },
  circularProgressDescription: {
    fontSize: wp(1.9),
    color: "rgba(255,255,255,0.8)",
    lineHeight: wp(2.5),
    alignSelf: "flex-start",
    marginLeft: wp(1),
  },
  taskCategoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    flex: 1,
    paddingLeft: wp(2),
  },
  taskCategoryCard: {
    width: "31%",
    height: hp(11.3),
    padding: wp(2),
    marginBottom: hp(1.2),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  taskCategoryTitle: {
    fontWeight: "bold",
    fontSize: wp(2.8),
    color: "black",
    marginBottom: hp(0.6),
  },
  taskCategoryProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp(0.3),
  },
  taskCategoryLinearProgressBar: {
    flex: 1,
    height: hp(0.7),
    borderRadius: hp(0.35),
    marginRight: wp(1),
  },
  taskCategoryProgressCounter: {
    fontSize: wp(2.5),
    color: "#000",
    fontWeight: "500",
  },

  // --- Total Transactions Section (Main Card) ---
  totalTransactionsContainer: {
    marginTop: hp(2),
    marginHorizontal: wp(3),
    paddingVertical: hp(1),
    paddingHorizontal: wp(1),
    backgroundColor: "#FFFFFF",
    borderRadius: wp(3),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },

  totalTransactionsTitle: {
    fontWeight: "bold",
    fontSize: hp(2.2),
    color: "#333333",
  },

  totalTransactionsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp(1.5),
  },

  viewReportsButton: {
    paddingVertical: hp(0.8),
    paddingHorizontal: wp(3),
    borderRadius: wp(1.5),
    borderWidth: 1,
    borderColor: "#E3781C",
    backgroundColor: "#FFFFFF",
  },

  viewReportsButtonText: {
    color: "#E3781C",
    fontSize: wp(3.2),
    fontWeight: "600",
  },

  barGraphContainer: {
    height: hp(35), // Increased height to accommodate the chart better

    borderRadius: wp(2),
    paddingHorizontal: wp(1),
    paddingVertical: hp(1),
    justifyContent: "center",
    marginTop: hp(1),
  },
  modalText: {
    marginVertical: "auto",
    fontSize: hp(2),
    color: "#000",
  },
  arrowStyle: {
    width: 20,
    height: 20,
    resizeMode: "contain",
    marginLeft: "auto",
  },
  tile: {
    flexDirection: "row",
    borderColor: "#DBDBDB",
    borderBottomWidth: 1,
    justifyContent: "space-between",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 10,
    width: 300,
    paddingHorizontal: 20,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  image: {
    height: hp(2),
    width: hp(2),
    marginRight: 5,
  },
});
